<?php

define('VIDEO_DOWNLOAD_URL','http://'.variable_get('cloudfront_domain',''));

/**
 * Implements hook_menu().
 */
function video_menu() {
  $items['admin/haproductions/video-settings'] = array(
    'title' => 'Video Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('video_settings_form'),
    'access arguments' => array('haproductions settings'),
    'file' => 'video.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function video_node_view($node, $view_mode, $langcode) {
	if($view_mode == 'full'){
		if(field_get_items('node', $node, 'field_youtube_id')){
			unset($node->content['field_images']);
		}
	}
}