<?php

define('VIDEO_DOWNLOAD_URL','http://'.variable_get('cloudfront_domain',''));

/**
 * Implements hook_menu().
 */
function video_menu() {
  $items['admin/haproductions/video-settings'] = array(
    'title' => 'Video Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('video_settings_form'),
    'access arguments' => array('haproductions settings'),
    'file' => 'video.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_node_load().
 */
function video_node_load($nodes, $types) {
  $types_we_want_to_process = array('video');

  // Decide whether any of $types are relevant to our purposes.
  if (count(array_intersect($types_we_want_to_process, $types))) {
  	foreach($nodes as $delta => $node){
  		$is_legacy = field_get_items('node', $node, 'field_legacy');
  		if($is_legacy){
  			$nodes[$delta]->is_legacy = $is_legacy[0]['value'];
  		}

  		$nodes[$delta]->non_anime = false;
  		if(field_get_items('node', $node, 'field_anime') === FALSE){
  			$nodes[$delta]->non_anime = true;
  		}
  	}
  }
}

/**
 * Implements hook_node_view().
 */
function video_node_view($node, $view_mode, $langcode) {
  if($node->type == 'video'){
    if($view_mode == 'sidebar'){
      $fields = array(
        'field_anime',
        'field_genre',
        'field_song',
        'field_band',
        'field_other',
      );
      foreach($fields as $field_name){
        $items = field_get_items('node', $node, $field_name);
        if($items !== FALSE){
          foreach($items as $delta => $item){
            $node->content[$field_name][$delta]['#href'] = 'video-listing/search/'.str_replace(' ','-',strtolower($item['taxonomy_term']->name));
          }
        }
      }
    }
  }
}