<?php

function jquery_cycle_libraries_info(){
	$libraries['jquery_cycle'] = array(
		'name' => 'jquery_cycle',
		'vendor url' => 'http://jquery.malsup.com/cycle2/',
		'download url' => 'http://malsup.github.io/min/jquery.cycle2.min.js',
	    'version arguments' => array(
	      'file' => 'jquery.cycle2.min.js',
	      'pattern' => '@jQuery\ Cycle2;\s+([0-9a-zA-Z\.-]+)@',
	      'lines' => 6,
	      'cols' => 66,
	    ),
	    'files' => array(
	    	'js' => array(
	    		'jquery.cycle2.min.js',
	    	),
	    ),
	);

	return $libraries;
}